# Generated by Django 4.2.6 on 2023-11-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('resumo', models.TextField()),
                ('linkimg', models.ImageField(upload_to='livros/')),
                ('pdf', models.FileField(upload_to='livros/')),
                ('nota', models.DecimalField(decimal_places=1, max_digits=3)),
                ('sub_categoria', models.CharField(blank=True, max_length=255)),
                ('estoque', models.IntegerField(null=True)),
                ('categoria', models.IntegerField(null=True)),
            ],
        ),
    ]
