# Generated by Django 4.2.6 on 2023-11-09 18:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Autor')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, null=True, verbose_name='Nome Editora')),
                ('livro_nome', models.CharField(max_length=255, null=True, verbose_name='Titulo Livro')),
            ],
            options={
                'verbose_name': 'Editora',
                'verbose_name_plural': 'Editoras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False, null=True)),
            ],
            options={
                'verbose_name': 'Statu',
                'verbose_name_plural': 'Status',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('resumo', models.TextField()),
                ('linkimg', models.ImageField(upload_to='livros/')),
                ('pdf', models.FileField(upload_to='livros/')),
                ('nota', models.DecimalField(decimal_places=1, max_digits=3)),
                ('sub_categoria', models.CharField(blank=True, max_length=255)),
                ('estoque', models.IntegerField(null=True)),
                ('categoria', models.IntegerField(null=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='angeline.autor', verbose_name='Autor')),
                ('editora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='angeline.editora', verbose_name='Editora')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='angeline.status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao_usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dissertacao', models.CharField(max_length=1000, null=True)),
                ('nota', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livro_avaliado', to='angeline.livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_avaliador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['usuario'],
            },
        ),
    ]
