# Generated by Django 4.2.6 on 2023-11-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0002_alter_livro_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='aluguel',
        ),
    ]
