# Generated by Django 4.2.6 on 2023-11-03 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0003_remove_livro_aluguel'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='aluguel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='angeline.aluguel'),
        ),
    ]
