autoajuda = {
    1: {
        "id":1,
        "nome":"A quietude é a chave",
        "resumo":"Explora a importância do equilíbrio e da reflexão na vida moderna, destacando como a serenidade pode levar a uma vida mais significativa.",
        "linkimg":"main/livros/autoajuda/aquietudeeachave.jpg",
        "pdf":"main/livros/autoajuda/aquietudeeachave.pdf",
        "nota": 10,
        "sub_categoria":"desenvolvimento pessoal",
        "estoque": 1,
        "categoria":1,
        },
    2: {
        "id":2,
        "nome":"Ative sua mente",
        "resumo":"Revela estratégias para otimizar o potencial mental, estimular a criatividade e alcançar o sucesso pessoal.",
        "linkimg":"main/livros/autoajuda/ativesuamente.jpg",
        "pdf":"main/livros/autoajuda/ativesuamente.pdf",
        "nota": 3.8,
        "sub_categoria":"desenvolvimento pessoal",
        "estoque": 1,
        "categoria":1,
        },
    3: {
        "id":3,
        "nome":"Como fazer amigos",
        "resumo":"Oferece conselhos sobre construir relacionamentos autênticos, comunicar eficazmente e criar conexões significativas.",
        "linkimg":"main/livros/autoajuda/comofazeramigos.jpg",
        "pdf":"main/livros/autoajuda/comofazeramigos.pdf",
        "nota": 6.2,
        "sub_categoria":"",
        "estoque": 1,
        "categoria":1,
        },
    4: {
        "id":4,
        "nome":"Coragem de não agradar",
        "resumo":"Aborda o p, mostrando como superar expectativas alheias e encontrar a verdadeira felicidade.",
        "linkimg":"main/livros/autoajuda/coragemdenaoagradar.jpg",
        "pdf":"main/livros/autoajuda/coragemdenaoagradar.pdf",
        "nota": 9.1,
        "sub_categoria":"desenvolvimento pessoal",
        "estoque": 1,
        "categoria":1,
        },
    5: {
        "id":5,
        "nome":"Limite zero",
        "resumo":"Explora o poder da técnica Ho'oponopono, que visa liberar traumas e alcançar a paz interior e cura pessoal.",
        "linkimg":"main/livros/autoajuda/limitezero.jpg",
        "pdf":"main/livros/autoajuda/limitezero.pdf",
        "nota": 2.5,
        "sub_categoria":"",
        "estoque": 1,
        "categoria":1,
        },
    6: {
        "id":6,
        "nome":"Mindset",
        "resumo":"Aborda como a mentalidade pode moldar o sucesso. Destaca a importância da mentalidade de crescimento.",
        "linkimg":"main/livros/autoajuda/mindset.jpg",
        "pdf":"main/livros/autoajuda/mindset.pdf",
        "nota": 8.3,
        "sub_categoria":"desenvolvimento pessoal",
        "estoque": 1,
        "categoria":1,
        },
    7: {
        "id":7,
        "nome":"O ego e seu inimigo",
        "resumo":"Aborda a autorreflexão, sugerindo que o ego pode ser um obstáculo ao crescimento pessoal e à paz interior.",
        "linkimg":"main/livros/autoajuda/oegoeseuinimigo.jpg",
        "pdf":"main/livros/autoajuda/oegoeseuinimigo.pdf",
        "nota": 5.7,
        "sub_categoria":"",
        "estoque": 1,
        "categoria":1,
        },
    8: {
        "id":8,
        "nome":"O milagre da manhã",
        "resumo":"Incentiva a rotina matinal para aumentar a produtividade, melhorar a saúde e alcançar objetivos pessoais.",
        "linkimg":"main/livros/autoajuda/omilagredamanha.jpg",
        "pdf":"main/livros/autoajuda/omilagredamanha.pdf",
        "nota": 4.2,
        "sub_categoria":"",
        "estoque": 1,
        "categoria":1,
        },
    9: {
        "id":9,
        "nome":"O poder do habito",
        "resumo":"Explora como os hábitos influenciam vidas e organizações, com insights sobre como mudá-los para o sucesso.",
        "linkimg":"main/livros/autoajuda/opoderdohabito.jpg",
        "pdf":"main/livros/autoajuda/opoderdohabito.pdf",
        "nota": 7.9,
        "sub_categoria":"desenvolvimento pessoal",
        "estoque": 1,
        "categoria":1,
        },
    10: {
        "id":10,
        "nome":"Procrastinação",
        "resumo":"Explora as causas da procrastinação e oferece estratégias para superá-la e alcançar maior produtividade e realização.",
        "linkimg":"main/livros/autoajuda/procrastinacao.jpg",
        "pdf":"main/livros/autoajuda/procratinacao.pdf",
        "nota": 1.6,
        "sub_categoria":"",
        "estoque": 1,
        "categoria":1,
        },
}
suspense = {
    11: {
        "id":11,
        "nome":"A Lista de Convidados",
        "resumo":" A Lista de Convidados é um romance que explora os segredos e relacionamentos de um grupo de amigos em uma festa de casamento, revelando intrigas e conflitos ocultos sob a superfície da celebração.",
        "linkimg":"main/livros/suspense/alistadeconvidados.jpeg",
        "pdf":"main/livros/suspense/alistadeconvidados.pdf",
        "nota": 3.4,
        "sub_categoria":"suspense adulto",
        "estoque": 1,
        "categoria":2,
    },
    12: {
        "id":12,
        "nome":"Bird Box",
        "resumo":"Bird Box é um thriller pós-apocalíptico em que os personagens precisam sobreviver usando vendas nos olhos para evitar ver criaturas misteriosas que induzem insanidade e morte.",
        "linkimg":"main/livros/suspense/birdbox.jpeg",
        "pdf":"main/livros/suspense/birdbox.pdf",
        "nota": 6.7,
        "sub_categoria":"suspense adulto",
        "estoque": 1,
        "categoria":2,
    },
    13: {
        "id":13,
        "nome":"Codigo da Vinci",
        "resumo":"O Código Da Vinci é um thriller que segue um simbologista e uma criptógrafa na busca por respostas sobre um segredo religioso envolvendo a linhagem de Jesus Cristo e o Santo Graal, desvendando conspirações e mistérios históricos.",
        "linkimg":"main/livros/suspense/codigodavinci.jpeg",
        "pdf":"main/livros/suspense/codigodavinci.pdf",
        "nota": 2.1,
        "sub_categoria":"suspense adulto",
        "estoque": 1,
        "categoria":2,
    },
    14: {
        "id":14,
        "nome":"E Não Sobrou Nenhum",
        "resumo": "E Não Sobrou Nenhum é um suspense em que dez estranhos convidados para uma ilha remota são assassinados um a um, revelando segredos e culpas ocultas durante a investigação sobre quem é o assassino.",
        "linkimg":"main/livros/suspense/enaosobrounenhum.jpeg",
        "pdf":"main/livros/suspense/enaosobrounenhum.pdf",
        "nota": 8.8,
        "sub_categoria":"",
        "estoque": 1,
        "categoria":2,
    },
    15: {
        "id":15,
        "nome":"Jantar Secreto",
        "resumo":"Jantar Secreto de Raphael Montes é um thriller que explora as reviravoltas sinistras na vida de quatro amigos que promovem jantares secretos, revelando segredos obscuros e crimes.",
        "linkimg":"main/livros/suspense/jantarsecreto.jpg",
        "pdf":"main/livros/suspense/jantarsecreto.pdf",
        "nota": 5.2,
        "sub_categoria":"",
        "estoque": 1,
        "categoria":2,
    },
    16: {
        "id":16,
        "nome":"Garota Exemplar",
        "resumo":"Amy Dunne desaparece, e seu marido, Nick, torna-se o principal suspeito. Um suspense psicológico envolvendo segredos sombrios, traição e reviravoltas chocantes.",
        "linkimg":"main/livros/suspense/garotaexemplar.jpg",
        "pdf":"main/livros/suspense/garotaexemplar.pdf",
        "nota": 9.4,
        "sub_categoria":"",
        "estoque": 1,
        "categoria":2,
    },
    17: {
        "id":17,
        "nome":"Manual de Assassino para Boas Garotas",
        "resumo":"Manual de Assassino para Boas Garotas é um livro de humor negro de Holly Jackson que narra as desventuras de Esther, uma jovem que se envolve em assassinatos acidentais e segue um manual bizarro para sobreviver.",
        "linkimg":"main/livros/suspense/manualdeassasinatoparaboasgarotas.jpeg",
        "pdf":"main/livros/suspense/manualdeassasinatoparaboasgarotas.pdf",
        "nota": 4.5,
        "sub_categoria":"",
        "estoque": 1,
        "categoria":2,
    },
    18: {
        "id":18,
        "nome":"O Que Aconteceu com Annie",
        "resumo":"O Que Aconteceu com Annie é um thriller de Lisa Jewell que explora o desaparecimento de uma adolescente e as revelações perturbadoras que surgem quando sua família começa a investigar seu paradeiro.",
        "linkimg":"main/livros/suspense/oqueaconteceucomannie.jpeg",
        "pdf":"main/livros/suspense/oqueaconteceucomannie.pdf",
        "nota": 7.2,
        "sub_categoria":"suspense adulto",
        "estoque": 1,
        "categoria":2,
    },
    19: {
        "id":19,
        "nome":"Suicidas",
        "resumo":"Suicidas é um romance de Raphael Montes que acompanha a investigação de um misterioso surto de suicídios na cidade de Contagem, revelando segredos obscuros e uma trama perturbadora.",
        "linkimg":"main/livros/suspense/suicidas.jpg",
        "pdf":"main/livros/suspense/suicidas.pdf",
        "nota": 1.9,
        "sub_categoria":"",
        "estoque": 1,
        "categoria":2,
    },
    20: {
        "id":20,
        "nome":"Verity",
        "resumo":"Verity é um suspense de Colleen Hoover que segue uma escritora que encontra o manuscrito inacabado de uma autora famosa e descobre segredos obscuros que ameaçam sua própria vida.",
        "linkimg":"main/livros/suspense/verity.jpeg",
        "pdf":"main/livros/suspense/verity.pdf",
        "nota": 6.3,
        "sub_categoria":"suspense adulto",
        "estoque": 1,
        "categoria":2,
    },
}
romance = {
    21: {
        "id":21,
        "nome":"É Assim Que Acaba",
        "resumo":"É Assim que Acaba de Colleen Hoover acompanha Lily Bloom enquanto ela busca superar traumas e encontrar cura emocional através do apoio de um amor do passado.",
        "linkimg":"main/livros/romance/eassimqueacaba.jpg",
        "pdf":"main/livros/romance/eassimqueacaba.pdf",
        "nota": 6.5,
        "sub_categoria":"",
        "estoque": 1,
        "categoria":3,
    },
    22: {
        "id":22,
        "nome":"A Razão do Amor",
        "resumo":"A Razão do Amor de Kristin Hannah explora a complicada relação entre duas irmãs enquanto enfrentam desafios pessoais e descobrem o verdadeiro significado do amor familiar, destacando temas de perdão e aceitação.",
        "linkimg":"main/livros/romance/arazaodoamor.jpg",
        "pdf":"main/livros/romance/arazaodoamor.pdf",
        "nota": 4.1,
        "sub_categoria":"",
        "estoque": 1,
        "categoria":3,
    },
    23: {
        "id":23,
        "nome":"As Mil Partes do Meu Coração.",
        "resumo":"As Mil Partes do Meu Coração de Colleen Hoover narra a vida de Merit Voss, uma jovem em uma família disfuncional, explorando temas de amor, perdão e aceitação em meio a segredos familiares sombrios.",
        "linkimg":"main/livros/romance/asmilpartesdomeucoracao.jpg",
        "pdf":"main/livros/romance/asmilpartesdomeucoracao.pdf",
        "nota": 7.8,
        "sub_categoria":"",
        "estoque": 1,
        "categoria":3,
    },
    24: {
        "id":24,
        "nome":"A Vida Invisivel de Addie Larue",
        "resumo":"A Vida Invisível de Addie Larue de V.E. Schwab segue a vida de Addie, amaldiçoada a ser esquecida por todos, enquanto busca significado e amor ao longo dos séculos.",
        "linkimg":"main/livros/romance/avidainvisiveldeaddielarue.jpg",
        "pdf":"main/livros/romance/avidainvisiveldeaddielarue.pdf",
        "nota": 3.2,
        "sub_categoria":"",
        "estoque": 1,
        "categoria":3,
    },
    25: {
        "id":25,
        "nome":"A Hipótese do Amor",
        "resumo":"Amy Dunne desaparece, e seu marido, Nick, torna-se o principal suspeito. Um suspense psicológico envolvendo segredos sombrios, traição e reviravoltas chocantes.",
        "linkimg":"main/livros/romance/ahipotesedoamor.jpg",
        "pdf":"main/livros/romance/ahipotesedoamor.pdf",
        "nota": 9.7,
        "sub_categoria":"",
        "estoque": 1,
        "categoria":3,
    },
    26: {
        "id":26,
        "nome":"Como Eu Era Antes de Você",
        "resumo":"Louisa é contratada como cuidadora de Will, um homem paralisado, e o livro aborda a transformação de suas vidas enquanto enfrentam desafios e desenvolvem um vínculo profundo.",
        "linkimg":"main/livros/romance/comoeueraantesdevoce.jpg",
        "pdf":"main/livros/romance/comoeueraantesdevoce.pdf",
        "nota": 9.9,
        "sub_categoria":"",
        "estoque": 1,
        "categoria":3,
    },
    27: {
        "id":27,
        "nome":"Daisy Jones & The Six",
        "resumo":"Daisy Jones & The Six de Taylor Jenkins Reid é uma narrativa fictícia sobre uma banda de rock dos anos 1970, contada por meio de entrevistas orais, explorando sua jornada, relacionamentos e criação de músicas icônicas.",
        "linkimg":"main/livros/romance/daisyjonesandthesix.jpg",
        "pdf":"main/livros/romance/daisyjonesandthesix.pdf",
        "nota": 8.2,
        "sub_categoria":"infantil",
        "estoque": 1,
        "categoria":3,
    },
    28: {
        "id":28,
        "nome":"Depois De Você",
        "resumo":"Depois de Você de Jojo Moyes é a continuação de 'Como Eu Era Antes de Você'. O livro acompanha a vida de Louisa Clark após a morte de Will, explorando seu processo de luto e como ela tenta seguir em frente.",
        "linkimg":"main/livros/romance/depoisdevoce.jpg",
        "pdf":"main/livros/romance/depoisdevoce.pdf",
        "nota": 2.9,
        "sub_categoria":"",
        "estoque": 1,
        "categoria":3,
    },
    29: {
        "id":29,
        "nome":"É Assim que Começa",
        "resumo":"É Assim que Começa é um livro de Colleen Hoover que narra a história de Kate e da relação com seu novo vizinho, Jesse, após um encontro inusitado. A trama explora segredos, amizade e o início de um amor improvável.",
        "linkimg":"main/livros/romance/eassimquecomeca.jpg",
        "pdf":"main/livros/romance/eassimquecomeca.pdf",
        "nota": 7.1,
        "sub_categoria":"",
        "estoque": 1,
        "categoria":3,
    },
    30: {
        "id":30,
        "nome":"Um Lugar Bem Longe Daqui",
        "resumo":"Um Lugar Bem Longe Daqui de Delia Owens narra a vida solitária de Kya Clark no pântano da Carolina do Norte, incluindo a descoberta de um corpo e uma investigação que desvenda segredos do passado.",
        "linkimg":"main/livros/romance/umlugarbemlongedaqui.jpg",
        "pdf":"main/livros/romance/umlugarbemlongedaqui.pdf",
        "nota": 4.8,
        "sub_categoria":"infantil",
        "estoque": 1,
        "categoria":3,
    },
}
biografias = {
    31: {
        "id":31,
        "nome":"A Marca da Vitória",
        "resumo":"O livro destaca a perseverança e a paixão de Knight pelo negócio e como ele construiu uma marca icônica.",
        "linkimg":"main/livros/biografias/amarcadavitoria.jpeg",
        "pdf":"main/livros/biografias/amarcadavitoria.pdf",
        "nota": 10,
       "sub_categoria":"",
        "estoque": 1,
        "categoria":4,
    },
    32: {
        "id":32,
        "nome":"Anne Frank",
        "resumo":"O Diário de Anne Frank é o relato comovente de Anne Frank, uma adolescente judia durante a Segunda Guerra Mundial, que descreve sua vida escondida dos nazistas em Amsterdã, oferecendo um testemunho impactante do Holocausto.",
        "linkimg":"main/livros/biografias/annefrank.jpeg",
        "pdf":"main/livros/biografias/annefrank.pdf",
        "nota": 6.4,
       "sub_categoria":"",
        "estoque": 1,
        "categoria":4,
    },
    33: {
        "id":33,
        "nome":"Elon Musk",
        "resumo":"Elon Musk Tesla, SpaceX e a Busca por um Futuro Fantástico narra a vida e a busca empreendedora de revolucionar indústrias em espacial, de veículos elétricos e solar, destacando seus desafios e sucessos notáveis.",
        "linkimg":"main/livros/biografias/elonmusk.jpeg",
        "pdf":"main/livros/biografias/elonmusk.pdf",
        "nota": 2.3,
       "sub_categoria":"",
        "estoque": 1,
        "categoria":4,
    },
    34: {
        "id":34,
        "nome":"Diana",
        "resumo":"O livro Diana é uma biografia da Princesa Diana, abordando sua vida, casamento com o Príncipe Charles, suas ações filantrópicas e sua trágica morte em 1997, proporcionando uma visão mais profunda da icônica figura real.",
        "linkimg":"main/livros/biografias/diana.jpeg",
        "pdf":"main/livros/biografias/diana.pdf",
        "nota": 8.7,
       "sub_categoria":"",
        "estoque": 1,
        "categoria":4,
    },
    35: {
        "id":35,
        "nome":"Eu Sou Malala",
        "resumo":"Eu Sou Malala narra a corajosa jornada de Malala Yousafzai, uma ativista paquistanesa que sobreviveu a um ataque do Talibã e se tornou uma defensora dos direitos das mulheres e da educação.",
        "linkimg":"main/livros/biografias/eusoumalala.jpeg",
        "pdf":"main/livros/biografias/eusoumalala.pdf",
        "nota": 3.7,
       "sub_categoria":"",
        "estoque": 1,
        "categoria":4,
    },
    36: {
        "id":36,
        "nome":"Leonardo Da Vinci",
        "resumo":"Leonardo da Vinci de Walter Isaacson é uma biografia que revela a vida e múltiplos talentos do gênio renascentista, explorando suas realizações como pintor, inventor e cientista, além de sua complexa personalidade.",
        "linkimg":"main/livros/biografias/leonardodavinci.jpeg",
        "pdf":"main/livros/biografias/leonardodavinci.pdf",
        "nota": 9.0,
       "sub_categoria":"",
        "estoque": 1,
        "categoria":4,
    },
    37: {
        "id":37,
        "nome":"Minha História",
        "resumo":"Minha História de Michelle Obama que explora sua jornada desde a infância em Chicago até os anos na Casa Branca, abordando temas de identidade, igualdade e suas experiências como mulher e mãe em uma posição de influência.",
        "linkimg":"main/livros/biografias/michelleobama.jpeg",
        "pdf":"main/livros/biografias/michelleobama.pdf",
        "nota": 1.8,
       "sub_categoria":"infantil",
        "estoque": 1,
        "categoria":4,
    },
    38: {
        "id":38,
        "nome":"Príncipe Harry",
        "resumo":"O que sobra começa com sua infância após a morte de sua mãe, a Princesa Diana, e aborda sua vida, decisão de se afastar da realeza britânica e relacionamento com Meghan Markle.",
        "linkimg":"main/livros/biografias/principeharry.jpeg",
        "pdf":"main/livros/biografias/principeharry.pdf",
        "nota": 7.5,
       "sub_categoria":"",
        "estoque": 1,
        "categoria":4,
    },
    39: {
        "id":39,
        "nome":"Rita Lee"
        ,"resumo":"Rita Lee é uma autobiografia que parece que você está dentro do livro, é transparente e muito divertido de se ler, ri muito em várias partes e chorei também em algumas.",
        "linkimg":"main/livros/biografias/ritalee.jpeg",
        "pdf":"main/livros/biografias/ritalee.pdf",
        "nota": 5.3,
       "sub_categoria":"",
        "estoque": 1,
        "categoria":4,
    },
    40: {
        "id":40,
        "nome":"Steve Jobs",
        "resumo":"Steve Jobs é uma biografia, revelando a vida e visão do cofundador da Apple, destacando sua paixão pela inovação, seu perfeccionismo e seu impacto duradouro na tecnologia e no design.",
        "linkimg":"main/livros/biografias/stevejobs.jpeg",
        "pdf":"main/livros/biografias/stevejobs.pdf",
        "nota": 4.0,
       "sub_categoria":"",
        "estoque": 1,
        "categoria":4,
    },
}
terror = {
    41: {
        "id":41,
        "nome":"Ao Cair da Noite",
        "resumo":"Ao Cair da Noite é um romance gótico de Shirley Jackson que narra a história de um casal que se muda para uma mansão isolada, onde eventos sinistros desencadeiam um suspense psicológico assustador.",
        "linkimg":"main/livros/terror/aocairdanoite.jpg",
        "pdf":"main/livros/terror/aocairdanoite.pdf",
        "nota": 5.9,
        "sub_categoria":"terror",
        "estoque": 1,
        "categoria":5,
    },
    42: {
        "id":42,
        "nome":"Belas Adormecidas",
        "resumo":"Belas Adormecidas é um romance de Stephen King e Owen King que explora um mundo onde as mulheres entram em sono profundo, desencadeando caos e desafios para os homens.",
        "linkimg":"main/livros/terror/belasadormecidas.webp",
        "pdf":"main/livros/terror/belasadormecidas.pdf",
        "nota": 3.0,
        "sub_categoria":"",
        "estoque": 1,
        "categoria":5,
    },
    43: {
        "id":43,
        "nome":"Carrie",
        "resumo":"Carrie é um romance de terror de Stephen King que conta a história de uma jovem com poderes telecinéticos que enfrenta o bullying e desencadeia uma tragédia sangrenta em sua cidade natal.",
        "linkimg":"main/livros/terror/carrie.jpg",
        "pdf":"main/livros/terror/carrie.pdf",
        "nota": 8.4,
        "sub_categoria":"terror",
        "estoque": 1,
        "categoria":5,
    },
    44: {
        "id":44,
        "nome":"Contos de Fadas",
        "resumo":"Contos de Fadas é uma coletânea de histórias clássicas que transporta os leitores para mundos mágicos cheios de personagens e eventos fantásticos, ensinando lições morais e entretendo gerações.",
        "linkimg":"main/livros/terror/contodefadas.jpg",
        "pdf":"main/livros/terror/contodefadas.pdf",
        "nota": 6.9,
        "sub_categoria":"",
        "estoque": 1,
        "categoria":5,
    },
    45: {
        "id":45,
        "nome":"Frankenstein",
        "resumo":"Frankenstein de Mary Shelley é um romance gótico que aborda a criação de um ser monstruoso por um cientista, explorando temas de ambição, alienação e responsabilidade, enquanto o monstro busca aceitação e vingança.",
        "linkimg":"main/livros/terror/frankstain.jpg",
        "pdf":"main/livros/terror/frankstain.pdf",
        "nota": 2.7,
        "sub_categoria":"",
        "estoque": 1,
        "categoria":5,
    },
    46: {
        "id":46,
        "nome":"Misery",
        "resumo":"Misery de Stephen King é um suspense psicológico que narra o pesadelo de um autor sequestrado por uma fã obsessiva que o força a escrever para ela, revelando uma relação doentia e a luta pela sobrevivência.",
        "linkimg":"main/livros/terror/misery.webp",
        "pdf":"main/livros/terror/misery.pdf",
        "nota": 7.6,
        "sub_categoria":"",
        "estoque": 1,
        "categoria":5,
    },
    47: {
        "id":47,
        "nome":"Morella",
        "resumo":"Morella é um conto de Edgar Allan Poe que explora a obsessão e a busca por imortalidade, onde uma mãe moribunda se funde com sua filha recém-nascida de forma macabra e sobrenatural.",
        "linkimg":"main/livros/terror/morella.jpg",
        "pdf":"main/livros/terror/morella.pdf",
        "nota": 4.3,
        "sub_categoria":"",
        "estoque": 1,
        "categoria":5,
    },
    48: {
        "id":48,
        "nome":"IT - A Coisa",
        "resumo":"Narra o confronto de um grupo de crianças com uma entidade maligna que assume diversas formas, incluindo o terrível palhaço Pennywise. Medo, amizade e coragem se entrelaçam nesta história aterrorizante.",
        "linkimg":"main/livros/terror/itacoisa.jpg",
        "pdf":"main/livros/terror/itacoisa.pdf",
        "nota": 9.3,
        "sub_categoria":"terror",
        "estoque": 1,
        "categoria":5,
    },
    49: {
        "id":49,
        "nome":"O Exorcista",
        "resumo":"O Exorcista de William Peter Blatty é um thriller de terror que segue a luta de um padre para salvar uma menina possuída pelo demônio, explorando temas de fé e possessão sobrenatural.",
        "linkimg":"main/livros/terror/oexorcista.jpg",
        "pdf":"main/livros/terror/oexorcista.pdf",
        "nota": 3.5,
        "sub_categoria":"terror",
        "estoque": 1,
        "categoria":5,
    },
    50: {
        "id":50,
        "nome":"O Retrato de Dorian Gray",
        "resumo":"O Retrato de Dorian Gray de Oscar Wilde é um romance que explora a corrupção moral de um jovem ao trocar sua juventude eterna por seus pecados, enquanto seu retrato envelhece em seu lugar.",
        "linkimg":"main/livros/terror/oretratodedoriangray.jpg",
        "pdf":"main/livros/terror/oretratodedoriangray.pdf",
        "nota": 6.1,
        "sub_categoria":"",
        "estoque": 1,
        "categoria":5,
    },
}
ficcao = {
    51: {
        "id":51,
        "nome":"Alice no País das Maravilhas",
        "resumo":"Alice cai em um mundo surreal e encontra personagens estranhos, como o Chapeleiro Maluco e a Rainha de Copas, explorando o absurdo e o ilógico",
        "linkimg":"main/livros/ficcao/alice.jpg",
        "pdf":"main/livros/ficcao/alice.pdf",
        "nota": 9.6,
        "sub_categoria":"infantil",
        "estoque": 1,
        "categoria":6,
    },
    52: {
        "id":52,
        "nome":"1984",
        "resumo":"1984 de George Orwell é uma distopia que retrata um regime totalitário controlado pelo Partido e seu líder, o Grande Irmão, onde a manipulação da verdade e a vigilância constante oprimem a liberdade individual.",
        "linkimg":"main/livros/ficcao/1984.jpg",
        "pdf":"main/livros/ficcao/1984.pdf",
        "nota": 4.7,
        "sub_categoria":"",
        "estoque": 1,
        "categoria":6,
    },
    53: {
        "id":53,
        "nome":"A Máquina do Tempo",
        "resumo":"A Máquina do Tempo de H.G. Wells é uma obra que narra a jornada de um cientista que inventa uma máquina capaz de viajar no tempo, explorando diferentes eras e revelando os desafios do futuro da humanidade.",
        "linkimg":"main/livros/ficcao/amaquinadotempo.jpg",
        "pdf":"main/livros/ficcao/amaquinadotempo.pdf",
        "nota": 2.0,
        "sub_categoria":"",
        "estoque": 1,
        "categoria":6,
    },
    54: {
        "id":54,
        "nome":"A Metamorfose",
        "resumo":"A Metamorfose de Franz Kafka descreve a transformação grotesca de Gregor Samsa em um inseto e as consequências disso em sua vida e relacionamentos familiares.",
        "linkimg":"main/livros/ficcao/ametamorfose.jpg",
        "pdf":"main/livros/ficcao/ametamorfose.pdf",
        "nota": 8.6,
        "sub_categoria":"terror",
        "estoque": 1,
        "categoria":6,
    },
    55: {
        "id":55,
        "nome":"A Revolução dos Bichos",
        "resumo":"A Revolução dos Bichos de George Orwell é uma fábula alegórica que retrata uma revolta de animais contra os humanos, que eventualmente leva a uma tirania ainda mais opressiva sob o comando dos próprios animais.",
        "linkimg":"main/livros/ficcao/arevolucaodosbichos.jpg",
        "pdf":"main/livros/ficcao/arevolucaodosbichos.pdf",
        "nota": 6.8,
        "sub_categoria":"",
        "estoque": 1,
        "categoria":6,
    },
    56: {
        "id":56,
        "nome":"Duna Saga",
        "resumo":"Duna Saga de Frank Herbert é uma epopeia de ficção científica que se desenrola no desértico planeta Duna, narrando a luta pelo controle de sua valiosa especiaria e as complexas tramas políticas e culturais envolvidas.",
        "linkimg":"main/livros/ficcao/dunasaga.jpg",
        "pdf":"main/livros/ficcao/dunasaga.pdf",
        "nota": 3.9,
        "sub_categoria":"",
        "estoque": 1,
        "categoria":6,
    },
    57: {
        "id":57,
        "nome":"Estilhaça-me",
        "resumo":"Estilhaça-me de Tahereh Mafi é uma distopia que segue a vida de Juliette, uma jovem com um toque letal, cuja jornada envolve o controle de seus poderes e um mundo distópico repleto de conspirações.",
        "linkimg":"main/livros/ficcao/estilhacame.jpg",
        "pdf":"main/livros/ficcao/estilhacame.pdf",
        "nota": 7.6,
        "sub_categoria":"",
        "estoque": 1,
        "categoria":6,
    },
    58: {
        "id":58,
        "nome":"Jogos Vorazes",
        "resumo":"Jogos Vorazes de Suzanne Collins é um livro de distopia que retrata um futuro sombrio onde jovens são obrigados a lutar até a morte em uma arena como entretenimento para a elite, enquanto uma heroína desafia o sistema opressivo.",
        "linkimg":"main/livros/ficcao/jogosvorazes.jpg",
        "pdf":"main/livros/ficcao/jogosvorazes.pdf",
        "nota": 5.1,
        "sub_categoria":"",
        "estoque": 1,
        "categoria":6,
    },
    59: {
        "id":59,
        "nome":"Liberta-me ",
        "resumo":"Liberta-me de Tahereh Mafi é o segundo livro da série 'Estilhaça-me', seguindo a saga de Juliette, uma jovem com poderes letais, enquanto ela lida com um mundo distópico e seu lugar nele.",
        "linkimg":"main/livros/ficcao/libertame.jpg",
        "pdf":"main/livros/ficcao/libertame.pdf",
        "nota": 2.6,
        "sub_categoria":"",
        "estoque": 1,
        "categoria":6,
    },
    60: {
        "id":60,
        "nome":"O Senhor dos Anéis",
        "resumo":"O Senhor dos Anéis de J.R.R. Tolkien é uma épica trilogia de fantasia que narra a jornada de Frodo e seus companheiros para destruir um poderoso anel que ameaça o mundo, enfrentando inúmeras adversidades e ameaças malignas.",
        "linkimg":"main/livros/ficcao/osenhordosaneis.jpg",
        "pdf":"main/livros/ficcao/osenhordosaneis.pdf",
        "nota": 7.7,
        "sub_categoria":"infantil",
        "estoque": 1,
        "categoria":6,
    },
}


dicionarios = {
    "Auto Ajuda": autoajuda,
    "Suspense": suspense,
    "Romance": romance,
    "Biografias": biografias,
    "Terror": terror,
    "Ficção": ficcao,
}

alugados = {}