acao = {
    1: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 7.4},
    2: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 3.8},
    3: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 6.2},
    4: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 9.1},
    5: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 2.5},
    6: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 8.3},
    7: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 5.7},
    8: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 4.2},
    9: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 7.9},
    10: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 1.6},
}
suspense = {
    1: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 3.4},
    2: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 6.7},
    3: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 2.1},
    4: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 8.8},
    5: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 5.2},
    6: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 9.4},
    7: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 4.5},
    8: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 7.2},
    9: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 1.9},
    10: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 6.3},
}
romance = {
    1: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 6.5},
    2: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 4.1},
    3: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 7.8},
    4: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 3.2},
    5: {"nome":"","resumo":"","linkimg":"main/livros/romance/ahipotesedoamor.jpg","pdf":"","nota": 9.7},
    6: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 5.6},
    7: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 8.2},
    8: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 2.9},
    9: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 7.1},
    10: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 4.8},
}
biografias = {
    1: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 4.6},
    2: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 6.4},
    3: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 2.3},
    4: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 8.7},
    5: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 3.7},
    6: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 9.0},
    7: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 1.8},
    8: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 7.5},
    9: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 5.3},
    10: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 4.0},
}
terror = {
    1: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 5.9},
    2: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 3.0},
    3: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 8.4},
    4: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 6.9},
    5: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 2.7},
    6: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 7.6},
    7: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 4.3},
    8: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 9.3},
    9: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 3.5},
    10: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 6.1},
}
ficcao = {
    1: {"nome":"Alice no País das Maravilhas","resumo":"Alice cai em um mundo surreal e encontra personagens estranhos, como o Chapeleiro Maluco e a Rainha de Copas, explorando o absurdo e o ilógico","linkimg":"main/livros/fantasia/alice.jpg","pdf":"","nota": 9.6},
    2: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 4.7},
    3: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 2.0},
    4: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 8.6},
    5: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 6.8},
    6: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 3.9},
    7: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 7.6},
    8: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 5.1},
    9: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 2.6},
    10: {"nome":"","resumo":"","linkimg":"","pdf":"","nota": 7.7},
}
